FROM maven:3.9.9-eclipse-temurin-17 AS builder
WORKDIR /build

COPY pom.xml                  .
COPY Core/pom.xml             Core/
COPY Producer/pom.xml         Producer/
COPY Consumer/pom.xml         Consumer/

COPY Core/src                 Core/src
COPY Producer/src             Producer/src
COPY Consumer/src             Consumer/src

RUN mvn clean install -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /build/Producer/target/Producer-*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]